### ISSUE TITLE
Will the pre-trained models be released?

### ISSUE THREAD

**Issue by tanshuai0219** [NickyFot/EmoCLIP#2]

**Comment by pritamqu** [comment]
+1

**Comment by NickyFot** [comment]
Thank you both for showing interest in our work!
I have added a link to the weights used for the backbone in the downstream task.

**Comment by SethGA** [comment]
Hi there,
I've downloaded the task weights and attempted to load the state dictionary into the model, but I encountered some missing keys related to the temporal transformer. A gist of a notebook can be found [here](https://gist.github.com/SethGA/9b842d93baf253f250a20271de38b77d)
Thanks for your attention :)

**Comment by NickyFot** [comment]
please set the number of layers to 2 when initialising the model (as described in the paper)
