### ISSUE TITLE
Downstream task weights are potentially missing layers

### ISSUE THREAD

**Issue by SethGA** [NickyFot/EmoCLIP#3]
Hi there,

I wrote the following on a closed issue, however I'm submitting a new issue for visibility.

> I've downloaded the task weights and attempted to load the state dictionary into the model, but I encountered some missing keys related to the temporal transformer. A gist of a notebook can be found [here](https://gist.github.com/SethGA/9b842d93baf253f250a20271de38b77d)

I really appreciate any help you may be able to offer in resolving this. I am eager to experiment with EmoCLIP :)
- Seth

**Comment by NickyFot** [comment]
Hey, this is a DDP/pytorch error; please see the relevant StackOverflow explanation [here](https://stackoverflow.com/questions/61854165/why-must-use-dataparallel-when-testing/61854807#61854807).

**Comment by SethGA** [comment]
Hi again,

Thank you for your quick reply! The issue I am raising is different from the `module.` prefix being present; in the gist I sent, after I load the weights, I do strip the `module.` prefix from the state dict. I realize that I should have cleared the output of the first cell to make this more clear. I am specifically referring to certain temporal transformer layers (e.g. `temporal.temporal_transformer.layers.2.0.fn.norm.weight`) that don't appear to be present in the state dict.

**Comment by NickyFot** [comment]
The default VClip() constructor initializes the network with 4 temporal layers, however, in the paper we specify that we use 2.

**Comment by qq1332427275** [comment]
Hi author, regarding the downstream weight checkpoint you posted, is that the checkpoint for the sota results on the MAFW dataset?

**Comment by NickyFot** [comment]
These are the weights used in the downstream task, pre-trained on MAFW.

**Comment by qq1332427275** [comment]
Thanks for your reply, MAFW has 5 folds, can you tell me which fold is the checkpoint?
